  server:
    port: 8080

  spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/web_spring"
        username: root
        password: root
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
  jwt:
     signerKey: "ySNpbNgfhp0qhva8AxLP3UaE/QpJf34bEG2NWPvIu+khhcS2JbfEZZ6LL6M+AYYn"